on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: sudo apt update
      - run: sudo apt install -y autoconf libglib2.0-dev libpixman-1-dev libsdl2-dev python2.7 build-essential
      - run: |
          ./configure \
            --with-coroutine=gthread \
            --disable-werror \
            --disable-mouse \
            --disable-cocoa \
            --enable-debug \
            --enable-sdl \
            --with-sdlabi=2.0 \
            --target-list=arm-softmmu \
            --extra-cflags=-DSTM32_UART_NO_BAUD_DELAY \
            --extra-ldflags=-g \
            --disable-vnc-jpeg \
            --disable-vnc-png \
            --disable-curses \
            --disable-gnutls \
            --disable-nettle \
            --disable-libssh2 \
            --disable-vnc-sasl \
            --disable-gcrypt \
            --disable-bzip2 \
            --disable-lzo \
            --disable-libusb \
            --python=/usr/bin/python2.7
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: qemu-system-arm-linux-${{ matrix.arch }}
          path: arm-softmmu/qemu-system-arm
      - uses: actions/upload-artifact@v4
        with:
          name: pc-bios-linux-${{ matrix.arch }}
          path: pc-bios/
